/*
// Licensed to Julian Hyde under one or more contributor license
// agreements. See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.
//
// Julian Hyde licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except in
// compliance with the License. You may obtain a copy of the License at:
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
*/
package org.eigenbase.oj.stmt;

import java.lang.reflect.*;
import java.util.List;

import openjava.ptree.*;

import org.eigenbase.rel.*;
import org.eigenbase.reltype.*;
import org.eigenbase.util.*;

import net.hydromatic.optiq.prepare.Prepare;


/**
 * PreparedExecution is a PreparedResult of a statement for which Java code was
 * generated by preparation.
 *
 * @author John V. Sichi
 * @version $Id$
 */
public class PreparedExecution extends Prepare.PreparedResultImpl {
    //~ Instance fields --------------------------------------------------------

    private final ParseTree parseTree;
    private final BoundMethod boundMethod;

    //~ Constructors -----------------------------------------------------------

    protected PreparedExecution(
        ParseTree parseTree,
        RelNode rootRel,
        RelDataType rowType,
        boolean isDml,
        TableModificationRel.Operation tableModOp,
        BoundMethod boundMethod,
        List<List<String>> fieldOrigins)
    {
        super(rowType, fieldOrigins, rootRel, tableModOp, isDml);
        this.parseTree = parseTree;
        this.boundMethod = boundMethod;
    }

    //~ Methods ----------------------------------------------------------------

    public String getCode()
    {
        return parseTree.toString();
    }

    public Method getMethod()
    {
        return boundMethod.method;
    }

    public Type getElementType()
    {
        return Object.class;
    }

    @Override
    public Object execute()
    {
        try {
            return boundMethod.call();
        } catch (IllegalAccessException e) {
            throw Util.newInternal(e);
        } catch (InvocationTargetException e) {
            throw Util.newInternal(e);
        }
    }

    public void setArgs(Object [] args)
    {
        boundMethod.args = args;
    }
}

// End PreparedExecution.java
