/*
// Licensed to DynamoBI Corporation (DynamoBI) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  DynamoBI licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at

//   http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.
*/
package org.eigenbase.oj.stmt;

import org.eigenbase.rel.*;


/**
 * PreparedResult represents the result of a call to OJPreparingStmt.prepareSql.
 *
 * @author John V. Sichi
 * @version $Id$
 */
public interface PreparedResult
{
    //~ Methods ----------------------------------------------------------------

    /**
     * @return the code generated by preparation
     */
    String getCode();

    /**
     * @return true iff this result is for a DML statement, in which case the
     * result set is one row with one column containing the number of rows
     * affected.
     */
    boolean isDml();

    /**
     * @return the table modification operation corresponding to this statement
     * if it is a table modification statement; otherwise null
     */
    TableModificationRel.Operation getTableModOp();

    /**
     * Executes the prepared result.
     *
     * @return producer of rows resulting from execution
     */
    Object execute();
}

// End PreparedResult.java
