#!/bin/bash
# sqlline - Script to launch SQL shell

# Build classpath on first call. (To force rebuild, remove .classpath.txt.)
cd $(dirname $0)
if [ ! -f .classpath.txt ]; then
    mvn dependency:build-classpath -Dmdep.outputFile=.classpath.txt
    awk -v RS=: -v ORS=: '{if(!m[$0]) {m[$0]=1; print}}' .classpath.txt */.classpath.txt > .fullclasspath.txt
fi

CP=
for module in core mongodb spark splunk; do
  CP=${CP}${module}/target/classes:
  CP=${CP}${module}/target/test-classes:
done

exec java -cp "${CP}$(cat .fullclasspath.txt)" sqlline.SqlLine "$@"

# End sqlline
