#!/bin/bash
# sqlline - Script to launch SQL shell
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Example:
# $ ./sqlline
# sqlline> !connect jdbc:calcite: admin admin

# Deduce whether we are running cygwin
case $(uname -s) in
(CYGWIN*) cygwin=true;;
(*) cygwin=;;
esac

if [ "$1" == "" ]; then
  export CPFILE=target/fullclasspath.txt
  # By default assume users want to use ES5
  EXCLUDED_PROJECTS="elasticsearch2"
elif [ $1 == "es2" ]; then
  export CPFILE=target/fullclasspath_$1.txt
  EXCLUDED_PROJECTS="elasticsearch5"
elif [ $1 == "es5" ]; then
  export CPFILE=target/fullclasspath_$1.txt
  EXCLUDED_PROJECTS="elasticsearch2"
else
  echo "Invalid argument: $1"
  exit 1
fi

shift

# Build classpath on first call.
# (To force rebuild, remove target/fullclasspath.txt.)
cd $(dirname $0)
if [ ! -f $CPFILE ]; then
    mvn -pl "!$EXCLUDED_PROJECTS" dependency:build-classpath -Dmdep.outputFile=target/classpath.txt
    awk -v RS=: -v ORS=: '{if (!m[$0]) {m[$0]=1; print}}' \
        target/classpath.txt \
        */target/classpath.txt > $CPFILE
fi

CP=
for module in core cassandra druid elasticsearch2 elasticsearch5 file mongodb spark splunk example/csv example/function; do
  CP=${CP}${module}/target/classes:
  CP=${CP}${module}/target/test-classes:
done

CP="${CP}$(cat $CPFILE)"

VM_OPTS=
if [ "$cygwin" ]; then
  CP=$(cygpath -wp "$CP")

  # Work around https://github.com/jline/jline2/issues/62
  VM_OPTS=-Djline.terminal=jline.UnixTerminal
fi

export JAVA_OPTS=-Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl

exec java $VM_OPTS -cp "${CP}" $JAVA_OPTS sqlline.SqlLine "$@"

# End sqlline
