/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * Platform for more complex tests of calcite. Such platform and test cases built on top of it
 * can help with lowering regressions establishing a common
 * ground for talking about the calcite behavior on specific cases (which can be described
 * through end2end tests).
 *
 * End 2 end means that the whole database is set up with meaningful data loaded and test through
 * SQL queries expressed via quidem framework gives valid results. We expect that such situations
 * can occur:
 * - some query gives invalid results
 * - some query generates error
 * Both situations can happen when Calcite implement and run the query incorrectly, that is why we
 * describe a quidem test with a result data.
 *
 * Tests should not check whether plans generated by calcite are specific - we do not want to test
 * how calcite works or optimizes its internals, rather we want to know if calcite produces
 * proper reliable results.
 */
@PackageMarker
package org.apache.calcite.chinook;

import org.apache.calcite.avatica.util.PackageMarker;

// End package-info.java
