/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.calcite.runtime;

import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.greaterThanOrEqualTo;
import static org.hamcrest.Matchers.lessThanOrEqualTo;

/**
 * Tests for {@link UuidFunction}.
 */
class UuidFunctionTest {

  /** Verifies that {@code UUIDV4()} produces version-4, IETF-variant UUIDs. */
  @Test void testUuidv4Version() {
    final UuidFunction f = new UuidFunction();
    for (int i = 0; i < 20; i++) {
      final UUID uuid = f.uuidv4();
      assertThat("version", uuid.version(), is(4));
      assertThat("variant", uuid.variant(), is(2)); // IETF = 2
    }
  }

  /** Verifies that {@code UUIDV7()} produces version-7, IETF-variant UUIDs. */
  @Test void testUuidv7Version() {
    final UuidFunction f = new UuidFunction();
    for (int i = 0; i < 20; i++) {
      final UUID uuid = f.uuidv7();
      assertThat("version", uuid.version(), is(7));
      assertThat("variant", uuid.variant(), is(2)); // IETF = 2
    }
  }

  /**
   * Verifies that the embedded timestamp in a {@code UUIDV7} UUID is within
   * a reasonable window of the real clock (within ±1 second).
   */
  @Test void testUuidv7Timestamp() {
    final UuidFunction f = new UuidFunction();
    final long before = System.currentTimeMillis();
    final UUID uuid = f.uuidv7();
    final long after = System.currentTimeMillis();

    // The 48-bit unix_ts_ms is the top 48 bits of mostSigBits,
    // i.e. mostSigBits >>> 16.
    final long embeddedMs = uuid.getMostSignificantBits() >>> 16;

    assertThat("embedded timestamp >= before", embeddedMs,
        greaterThanOrEqualTo(before));
    // allow up to 1 s ahead (due to counter overflow advancing the clock)
    assertThat("embedded timestamp <= after + 1000", embeddedMs,
        lessThanOrEqualTo(after + 1000));
  }

  /**
   * Verifies that UUIDs generated by consecutive calls to {@code UUIDV7()}
   * are strictly increasing (monotonic) when compared as 128-bit unsigned
   * integers, which is the sortability guarantee of RFC 9562 §6.2.
   *
   * <p>We generate 4 096 UUIDs in a tight loop to exercise the within-ms
   * counter path.
   */
  @Test void testUuidv7Monotonicity() {
    final UuidFunction f = new UuidFunction();
    final int count = 4096;
    final List<UUID> uuids = new ArrayList<>(count);
    for (int i = 0; i < count; i++) {
      uuids.add(f.uuidv7());
    }
    for (int i = 1; i < count; i++) {
      final UUID prev = uuids.get(i - 1);
      final UUID curr = uuids.get(i);
      // UUID natural ordering uses unsigned comparison of the 128-bit value.
      assertThat("UUID[" + i + "] > UUID[" + (i - 1) + "]",
          curr.compareTo(prev), greaterThanOrEqualTo(1));
    }
  }

  /**
   * Verifies that the 12-bit rand_a field is properly masked and never exceeds
   * its capacity (0x0FFF = 4095).
   */
  @Test void testUuidv7RandAField() {
    final UuidFunction f = new UuidFunction();
    for (int i = 0; i < 100; i++) {
      final UUID uuid = f.uuidv7();
      final long randA = uuid.getMostSignificantBits() & 0x0FFFL;
      assertThat("rand_a <= 0x0FFF", randA, lessThanOrEqualTo(0x0FFFL));
    }
  }
}
