/* Generated By:JavaCC: Do not edit this line. SqlParserImplConstants.java */
package org.eigenbase.sql.parser.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int A = 1;
  /** RegularExpression Id. */
  int ABS = 2;
  /** RegularExpression Id. */
  int ABSOLUTE = 3;
  /** RegularExpression Id. */
  int ACTION = 4;
  /** RegularExpression Id. */
  int ADA = 5;
  /** RegularExpression Id. */
  int ADD = 6;
  /** RegularExpression Id. */
  int ADMIN = 7;
  /** RegularExpression Id. */
  int AFTER = 8;
  /** RegularExpression Id. */
  int ALL = 9;
  /** RegularExpression Id. */
  int ALLOCATE = 10;
  /** RegularExpression Id. */
  int ALLOW = 11;
  /** RegularExpression Id. */
  int ALWAYS = 12;
  /** RegularExpression Id. */
  int ALTER = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int ANY = 15;
  /** RegularExpression Id. */
  int ARE = 16;
  /** RegularExpression Id. */
  int ARRAY = 17;
  /** RegularExpression Id. */
  int AS = 18;
  /** RegularExpression Id. */
  int ASC = 19;
  /** RegularExpression Id. */
  int ASENSITIVE = 20;
  /** RegularExpression Id. */
  int ASSERTION = 21;
  /** RegularExpression Id. */
  int ASSIGNMENT = 22;
  /** RegularExpression Id. */
  int ASYMMETRIC = 23;
  /** RegularExpression Id. */
  int AT = 24;
  /** RegularExpression Id. */
  int ATOMIC = 25;
  /** RegularExpression Id. */
  int ATTRIBUTE = 26;
  /** RegularExpression Id. */
  int ATTRIBUTES = 27;
  /** RegularExpression Id. */
  int AUTHORIZATION = 28;
  /** RegularExpression Id. */
  int AVG = 29;
  /** RegularExpression Id. */
  int BEFORE = 30;
  /** RegularExpression Id. */
  int BEGIN = 31;
  /** RegularExpression Id. */
  int BERNOULLI = 32;
  /** RegularExpression Id. */
  int BETWEEN = 33;
  /** RegularExpression Id. */
  int BIGINT = 34;
  /** RegularExpression Id. */
  int BINARY = 35;
  /** RegularExpression Id. */
  int BIT = 36;
  /** RegularExpression Id. */
  int BLOB = 37;
  /** RegularExpression Id. */
  int BOOLEAN = 38;
  /** RegularExpression Id. */
  int BOTH = 39;
  /** RegularExpression Id. */
  int BREADTH = 40;
  /** RegularExpression Id. */
  int BY = 41;
  /** RegularExpression Id. */
  int C = 42;
  /** RegularExpression Id. */
  int CALL = 43;
  /** RegularExpression Id. */
  int CALLED = 44;
  /** RegularExpression Id. */
  int CARDINALITY = 45;
  /** RegularExpression Id. */
  int CASCADE = 46;
  /** RegularExpression Id. */
  int CASCADED = 47;
  /** RegularExpression Id. */
  int CASE = 48;
  /** RegularExpression Id. */
  int CAST = 49;
  /** RegularExpression Id. */
  int CATALOG = 50;
  /** RegularExpression Id. */
  int CATALOG_NAME = 51;
  /** RegularExpression Id. */
  int CEIL = 52;
  /** RegularExpression Id. */
  int CEILING = 53;
  /** RegularExpression Id. */
  int CHAIN = 54;
  /** RegularExpression Id. */
  int CHAR = 55;
  /** RegularExpression Id. */
  int CHAR_LENGTH = 56;
  /** RegularExpression Id. */
  int CHARACTER = 57;
  /** RegularExpression Id. */
  int CHARACTER_LENGTH = 58;
  /** RegularExpression Id. */
  int CHARACTER_SET_CATALOG = 59;
  /** RegularExpression Id. */
  int CHARACTER_SET_NAME = 60;
  /** RegularExpression Id. */
  int CHARACTER_SET_SCHEMA = 61;
  /** RegularExpression Id. */
  int CHARACTERISTICS = 62;
  /** RegularExpression Id. */
  int CHARACTERS = 63;
  /** RegularExpression Id. */
  int CHECK = 64;
  /** RegularExpression Id. */
  int CLASS_ORIGIN = 65;
  /** RegularExpression Id. */
  int CLOB = 66;
  /** RegularExpression Id. */
  int CLOSE = 67;
  /** RegularExpression Id. */
  int COALESCE = 68;
  /** RegularExpression Id. */
  int COBOL = 69;
  /** RegularExpression Id. */
  int COLLATE = 70;
  /** RegularExpression Id. */
  int COLLATION = 71;
  /** RegularExpression Id. */
  int COLLATION_CATALOG = 72;
  /** RegularExpression Id. */
  int COLLATION_NAME = 73;
  /** RegularExpression Id. */
  int COLLATION_SCHEMA = 74;
  /** RegularExpression Id. */
  int COLLECT = 75;
  /** RegularExpression Id. */
  int COLUMN = 76;
  /** RegularExpression Id. */
  int COLUMN_NAME = 77;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION = 78;
  /** RegularExpression Id. */
  int COMMAND_FUNCTION_CODE = 79;
  /** RegularExpression Id. */
  int COMMIT = 80;
  /** RegularExpression Id. */
  int COMMITTED = 81;
  /** RegularExpression Id. */
  int CONDITION = 82;
  /** RegularExpression Id. */
  int CONDITION_NUMBER = 83;
  /** RegularExpression Id. */
  int CONNECT = 84;
  /** RegularExpression Id. */
  int CONNECTION = 85;
  /** RegularExpression Id. */
  int CONNECTION_NAME = 86;
  /** RegularExpression Id. */
  int CONSTRAINT = 87;
  /** RegularExpression Id. */
  int CONSTRAINT_CATALOG = 88;
  /** RegularExpression Id. */
  int CONSTRAINT_NAME = 89;
  /** RegularExpression Id. */
  int CONSTRAINT_SCHEMA = 90;
  /** RegularExpression Id. */
  int CONSTRAINTS = 91;
  /** RegularExpression Id. */
  int CONSTRUCTOR = 92;
  /** RegularExpression Id. */
  int CONTAINS = 93;
  /** RegularExpression Id. */
  int CONVERT = 94;
  /** RegularExpression Id. */
  int CONTINUE = 95;
  /** RegularExpression Id. */
  int CORR = 96;
  /** RegularExpression Id. */
  int CORRESPONDING = 97;
  /** RegularExpression Id. */
  int COUNT = 98;
  /** RegularExpression Id. */
  int COVAR_POP = 99;
  /** RegularExpression Id. */
  int COVAR_SAMP = 100;
  /** RegularExpression Id. */
  int CREATE = 101;
  /** RegularExpression Id. */
  int CROSS = 102;
  /** RegularExpression Id. */
  int CUBE = 103;
  /** RegularExpression Id. */
  int CUME_DIST = 104;
  /** RegularExpression Id. */
  int CURRENT = 105;
  /** RegularExpression Id. */
  int CURRENT_CATALOG = 106;
  /** RegularExpression Id. */
  int CURRENT_DATE = 107;
  /** RegularExpression Id. */
  int CURRENT_DEFAULT_TRANSFORM_GROUP = 108;
  /** RegularExpression Id. */
  int CURRENT_PATH = 109;
  /** RegularExpression Id. */
  int CURRENT_ROLE = 110;
  /** RegularExpression Id. */
  int CURRENT_SCHEMA = 111;
  /** RegularExpression Id. */
  int CURRENT_TIME = 112;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 113;
  /** RegularExpression Id. */
  int CURRENT_TRANSFORM_GROUP_FOR_TYPE = 114;
  /** RegularExpression Id. */
  int CURRENT_USER = 115;
  /** RegularExpression Id. */
  int CURSOR = 116;
  /** RegularExpression Id. */
  int CURSOR_NAME = 117;
  /** RegularExpression Id. */
  int CYCLE = 118;
  /** RegularExpression Id. */
  int DATA = 119;
  /** RegularExpression Id. */
  int DATE = 120;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_CODE = 121;
  /** RegularExpression Id. */
  int DATETIME_INTERVAL_PRECISION = 122;
  /** RegularExpression Id. */
  int DAY = 123;
  /** RegularExpression Id. */
  int DEALLOCATE = 124;
  /** RegularExpression Id. */
  int DEC = 125;
  /** RegularExpression Id. */
  int DECIMAL = 126;
  /** RegularExpression Id. */
  int DECLARE = 127;
  /** RegularExpression Id. */
  int DEFAULT_KW = 128;
  /** RegularExpression Id. */
  int DEFAULTS = 129;
  /** RegularExpression Id. */
  int DEFERRABLE = 130;
  /** RegularExpression Id. */
  int DEFERRED = 131;
  /** RegularExpression Id. */
  int DEFINED = 132;
  /** RegularExpression Id. */
  int DEFINER = 133;
  /** RegularExpression Id. */
  int DEGREE = 134;
  /** RegularExpression Id. */
  int DELETE = 135;
  /** RegularExpression Id. */
  int DENSE_RANK = 136;
  /** RegularExpression Id. */
  int DEPTH = 137;
  /** RegularExpression Id. */
  int DEREF = 138;
  /** RegularExpression Id. */
  int DERIVED = 139;
  /** RegularExpression Id. */
  int DESCRIBE = 140;
  /** RegularExpression Id. */
  int DESC = 141;
  /** RegularExpression Id. */
  int DESCRIPTION = 142;
  /** RegularExpression Id. */
  int DESCRIPTOR = 143;
  /** RegularExpression Id. */
  int DETERMINISTIC = 144;
  /** RegularExpression Id. */
  int DIAGNOSTICS = 145;
  /** RegularExpression Id. */
  int DISALLOW = 146;
  /** RegularExpression Id. */
  int DISCONNECT = 147;
  /** RegularExpression Id. */
  int DISPATCH = 148;
  /** RegularExpression Id. */
  int DISTINCT = 149;
  /** RegularExpression Id. */
  int DOMAIN = 150;
  /** RegularExpression Id. */
  int DOUBLE = 151;
  /** RegularExpression Id. */
  int DROP = 152;
  /** RegularExpression Id. */
  int DYNAMIC = 153;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION = 154;
  /** RegularExpression Id. */
  int DYNAMIC_FUNCTION_CODE = 155;
  /** RegularExpression Id. */
  int EACH = 156;
  /** RegularExpression Id. */
  int ELEMENT = 157;
  /** RegularExpression Id. */
  int ELSE = 158;
  /** RegularExpression Id. */
  int END = 159;
  /** RegularExpression Id. */
  int END_EXEC = 160;
  /** RegularExpression Id. */
  int EQUALS = 161;
  /** RegularExpression Id. */
  int ESCAPE = 162;
  /** RegularExpression Id. */
  int EVERY = 163;
  /** RegularExpression Id. */
  int EXCEPT = 164;
  /** RegularExpression Id. */
  int EXCEPTION = 165;
  /** RegularExpression Id. */
  int EXCLUDE = 166;
  /** RegularExpression Id. */
  int EXCLUDING = 167;
  /** RegularExpression Id. */
  int EXEC = 168;
  /** RegularExpression Id. */
  int EXECUTE = 169;
  /** RegularExpression Id. */
  int EXISTS = 170;
  /** RegularExpression Id. */
  int EXP = 171;
  /** RegularExpression Id. */
  int EXPLAIN = 172;
  /** RegularExpression Id. */
  int EXTERNAL = 173;
  /** RegularExpression Id. */
  int EXTRACT = 174;
  /** RegularExpression Id. */
  int FALSE = 175;
  /** RegularExpression Id. */
  int FETCH = 176;
  /** RegularExpression Id. */
  int FILTER = 177;
  /** RegularExpression Id. */
  int FINAL = 178;
  /** RegularExpression Id. */
  int FIRST = 179;
  /** RegularExpression Id. */
  int FIRST_VALUE = 180;
  /** RegularExpression Id. */
  int FLOAT = 181;
  /** RegularExpression Id. */
  int FLOOR = 182;
  /** RegularExpression Id. */
  int FOLLOWING = 183;
  /** RegularExpression Id. */
  int FOR = 184;
  /** RegularExpression Id. */
  int FOREIGN = 185;
  /** RegularExpression Id. */
  int FORTRAN = 186;
  /** RegularExpression Id. */
  int FOUND = 187;
  /** RegularExpression Id. */
  int FREE = 188;
  /** RegularExpression Id. */
  int FROM = 189;
  /** RegularExpression Id. */
  int FULL = 190;
  /** RegularExpression Id. */
  int FUNCTION = 191;
  /** RegularExpression Id. */
  int FUSION = 192;
  /** RegularExpression Id. */
  int G = 193;
  /** RegularExpression Id. */
  int GENERAL = 194;
  /** RegularExpression Id. */
  int GENERATED = 195;
  /** RegularExpression Id. */
  int GET = 196;
  /** RegularExpression Id. */
  int GLOBAL = 197;
  /** RegularExpression Id. */
  int GO = 198;
  /** RegularExpression Id. */
  int GOTO = 199;
  /** RegularExpression Id. */
  int GRANT = 200;
  /** RegularExpression Id. */
  int GRANTED = 201;
  /** RegularExpression Id. */
  int GROUP = 202;
  /** RegularExpression Id. */
  int GROUPING = 203;
  /** RegularExpression Id. */
  int HAVING = 204;
  /** RegularExpression Id. */
  int HIERARCHY = 205;
  /** RegularExpression Id. */
  int HOLD = 206;
  /** RegularExpression Id. */
  int HOUR = 207;
  /** RegularExpression Id. */
  int IDENTITY = 208;
  /** RegularExpression Id. */
  int IMMEDIATE = 209;
  /** RegularExpression Id. */
  int IMPLEMENTATION = 210;
  /** RegularExpression Id. */
  int IMPORT = 211;
  /** RegularExpression Id. */
  int IN = 212;
  /** RegularExpression Id. */
  int INDICATOR = 213;
  /** RegularExpression Id. */
  int INCLUDING = 214;
  /** RegularExpression Id. */
  int INCREMENT = 215;
  /** RegularExpression Id. */
  int INITIALLY = 216;
  /** RegularExpression Id. */
  int INNER = 217;
  /** RegularExpression Id. */
  int INOUT = 218;
  /** RegularExpression Id. */
  int INPUT = 219;
  /** RegularExpression Id. */
  int INSENSITIVE = 220;
  /** RegularExpression Id. */
  int INSERT = 221;
  /** RegularExpression Id. */
  int INSTANCE = 222;
  /** RegularExpression Id. */
  int INSTANTIABLE = 223;
  /** RegularExpression Id. */
  int INT = 224;
  /** RegularExpression Id. */
  int INTEGER = 225;
  /** RegularExpression Id. */
  int INTERSECT = 226;
  /** RegularExpression Id. */
  int INTERSECTION = 227;
  /** RegularExpression Id. */
  int INTERVAL = 228;
  /** RegularExpression Id. */
  int INTO = 229;
  /** RegularExpression Id. */
  int INVOKER = 230;
  /** RegularExpression Id. */
  int IS = 231;
  /** RegularExpression Id. */
  int ISOLATION = 232;
  /** RegularExpression Id. */
  int JAVA = 233;
  /** RegularExpression Id. */
  int JOIN = 234;
  /** RegularExpression Id. */
  int K = 235;
  /** RegularExpression Id. */
  int KEY = 236;
  /** RegularExpression Id. */
  int KEY_MEMBER = 237;
  /** RegularExpression Id. */
  int KEY_TYPE = 238;
  /** RegularExpression Id. */
  int LABEL = 239;
  /** RegularExpression Id. */
  int LANGUAGE = 240;
  /** RegularExpression Id. */
  int LARGE = 241;
  /** RegularExpression Id. */
  int LAST = 242;
  /** RegularExpression Id. */
  int LAST_VALUE = 243;
  /** RegularExpression Id. */
  int LATERAL = 244;
  /** RegularExpression Id. */
  int LEADING = 245;
  /** RegularExpression Id. */
  int LEFT = 246;
  /** RegularExpression Id. */
  int LENGTH = 247;
  /** RegularExpression Id. */
  int LEVEL = 248;
  /** RegularExpression Id. */
  int LIBRARY = 249;
  /** RegularExpression Id. */
  int LIKE = 250;
  /** RegularExpression Id. */
  int LIMIT = 251;
  /** RegularExpression Id. */
  int LN = 252;
  /** RegularExpression Id. */
  int LOCAL = 253;
  /** RegularExpression Id. */
  int LOCALTIME = 254;
  /** RegularExpression Id. */
  int LOCALTIMESTAMP = 255;
  /** RegularExpression Id. */
  int LOCATOR = 256;
  /** RegularExpression Id. */
  int LOWER = 257;
  /** RegularExpression Id. */
  int M = 258;
  /** RegularExpression Id. */
  int MAP = 259;
  /** RegularExpression Id. */
  int MATCH = 260;
  /** RegularExpression Id. */
  int MATCHED = 261;
  /** RegularExpression Id. */
  int MAX = 262;
  /** RegularExpression Id. */
  int MAXVALUE = 263;
  /** RegularExpression Id. */
  int MEMBER = 264;
  /** RegularExpression Id. */
  int MERGE = 265;
  /** RegularExpression Id. */
  int MESSAGE_LENGTH = 266;
  /** RegularExpression Id. */
  int MESSAGE_OCTET_LENGTH = 267;
  /** RegularExpression Id. */
  int MESSAGE_TEXT = 268;
  /** RegularExpression Id. */
  int METHOD = 269;
  /** RegularExpression Id. */
  int MIN = 270;
  /** RegularExpression Id. */
  int MINUTE = 271;
  /** RegularExpression Id. */
  int MINVALUE = 272;
  /** RegularExpression Id. */
  int MOD = 273;
  /** RegularExpression Id. */
  int MODIFIES = 274;
  /** RegularExpression Id. */
  int MODULE = 275;
  /** RegularExpression Id. */
  int MONTH = 276;
  /** RegularExpression Id. */
  int MORE_KW = 277;
  /** RegularExpression Id. */
  int MULTISET = 278;
  /** RegularExpression Id. */
  int MUMPS = 279;
  /** RegularExpression Id. */
  int NAME = 280;
  /** RegularExpression Id. */
  int NAMES = 281;
  /** RegularExpression Id. */
  int NATIONAL = 282;
  /** RegularExpression Id. */
  int NATURAL = 283;
  /** RegularExpression Id. */
  int NCHAR = 284;
  /** RegularExpression Id. */
  int NCLOB = 285;
  /** RegularExpression Id. */
  int NESTING = 286;
  /** RegularExpression Id. */
  int NEW = 287;
  /** RegularExpression Id. */
  int NEXT = 288;
  /** RegularExpression Id. */
  int NO = 289;
  /** RegularExpression Id. */
  int NONE = 290;
  /** RegularExpression Id. */
  int NORMALIZE = 291;
  /** RegularExpression Id. */
  int NORMALIZED = 292;
  /** RegularExpression Id. */
  int NOT = 293;
  /** RegularExpression Id. */
  int NULL = 294;
  /** RegularExpression Id. */
  int NULLABLE = 295;
  /** RegularExpression Id. */
  int NULLIF = 296;
  /** RegularExpression Id. */
  int NULLS = 297;
  /** RegularExpression Id. */
  int NUMBER = 298;
  /** RegularExpression Id. */
  int NUMERIC = 299;
  /** RegularExpression Id. */
  int OBJECT = 300;
  /** RegularExpression Id. */
  int OCTET_LENGTH = 301;
  /** RegularExpression Id. */
  int OCTETS = 302;
  /** RegularExpression Id. */
  int OF = 303;
  /** RegularExpression Id. */
  int OLD = 304;
  /** RegularExpression Id. */
  int ON = 305;
  /** RegularExpression Id. */
  int ONLY = 306;
  /** RegularExpression Id. */
  int OPEN = 307;
  /** RegularExpression Id. */
  int OPTION = 308;
  /** RegularExpression Id. */
  int OPTIONS = 309;
  /** RegularExpression Id. */
  int OR = 310;
  /** RegularExpression Id. */
  int ORDER = 311;
  /** RegularExpression Id. */
  int ORDERING = 312;
  /** RegularExpression Id. */
  int ORDINALITY = 313;
  /** RegularExpression Id. */
  int OTHERS = 314;
  /** RegularExpression Id. */
  int OUT = 315;
  /** RegularExpression Id. */
  int OUTER = 316;
  /** RegularExpression Id. */
  int OUTPUT = 317;
  /** RegularExpression Id. */
  int OVER = 318;
  /** RegularExpression Id. */
  int OVERLAPS = 319;
  /** RegularExpression Id. */
  int OVERLAY = 320;
  /** RegularExpression Id. */
  int OVERRIDING = 321;
  /** RegularExpression Id. */
  int PAD = 322;
  /** RegularExpression Id. */
  int PARAMETER = 323;
  /** RegularExpression Id. */
  int PARAMETER_MODE = 324;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 325;
  /** RegularExpression Id. */
  int PARAMETER_ORDINAL_POSITION = 326;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_CATALOG = 327;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_NAME = 328;
  /** RegularExpression Id. */
  int PARAMETER_SPECIFIC_SCHEMA = 329;
  /** RegularExpression Id. */
  int PARTIAL = 330;
  /** RegularExpression Id. */
  int PARTITION = 331;
  /** RegularExpression Id. */
  int PASCAL = 332;
  /** RegularExpression Id. */
  int PASSTHROUGH = 333;
  /** RegularExpression Id. */
  int PATH = 334;
  /** RegularExpression Id. */
  int PERCENT_RANK = 335;
  /** RegularExpression Id. */
  int PERCENTILE_CONT = 336;
  /** RegularExpression Id. */
  int PERCENTILE_DISC = 337;
  /** RegularExpression Id. */
  int PLACING = 338;
  /** RegularExpression Id. */
  int PLAN = 339;
  /** RegularExpression Id. */
  int PLI = 340;
  /** RegularExpression Id. */
  int POSITION = 341;
  /** RegularExpression Id. */
  int POWER = 342;
  /** RegularExpression Id. */
  int PRECEDING = 343;
  /** RegularExpression Id. */
  int PRECISION = 344;
  /** RegularExpression Id. */
  int PREPARE = 345;
  /** RegularExpression Id. */
  int PRESERVE = 346;
  /** RegularExpression Id. */
  int PRIMARY = 347;
  /** RegularExpression Id. */
  int PRIOR = 348;
  /** RegularExpression Id. */
  int PRIVILEGES = 349;
  /** RegularExpression Id. */
  int PROCEDURE = 350;
  /** RegularExpression Id. */
  int PUBLIC = 351;
  /** RegularExpression Id. */
  int RANGE = 352;
  /** RegularExpression Id. */
  int RANK = 353;
  /** RegularExpression Id. */
  int READ = 354;
  /** RegularExpression Id. */
  int READS = 355;
  /** RegularExpression Id. */
  int REAL = 356;
  /** RegularExpression Id. */
  int RECURSIVE = 357;
  /** RegularExpression Id. */
  int REF = 358;
  /** RegularExpression Id. */
  int REFERENCES = 359;
  /** RegularExpression Id. */
  int REFERENCING = 360;
  /** RegularExpression Id. */
  int REGR_AVGX = 361;
  /** RegularExpression Id. */
  int REGR_AVGY = 362;
  /** RegularExpression Id. */
  int REGR_COUNT = 363;
  /** RegularExpression Id. */
  int REGR_INTERCEPT = 364;
  /** RegularExpression Id. */
  int REGR_R2 = 365;
  /** RegularExpression Id. */
  int REGR_SLOPE = 366;
  /** RegularExpression Id. */
  int REGR_SXX = 367;
  /** RegularExpression Id. */
  int REGR_SXY = 368;
  /** RegularExpression Id. */
  int RELATIVE = 369;
  /** RegularExpression Id. */
  int RELEASE = 370;
  /** RegularExpression Id. */
  int REPEATABLE = 371;
  /** RegularExpression Id. */
  int RESTART = 372;
  /** RegularExpression Id. */
  int RESTRICT = 373;
  /** RegularExpression Id. */
  int RESULT = 374;
  /** RegularExpression Id. */
  int RETURN = 375;
  /** RegularExpression Id. */
  int RETURNED_CARDINALITY = 376;
  /** RegularExpression Id. */
  int RETURNED_LENGTH = 377;
  /** RegularExpression Id. */
  int RETURNED_OCTET_LENGTH = 378;
  /** RegularExpression Id. */
  int RETURNED_SQLSTATE = 379;
  /** RegularExpression Id. */
  int RETURNS = 380;
  /** RegularExpression Id. */
  int REVOKE = 381;
  /** RegularExpression Id. */
  int RIGHT = 382;
  /** RegularExpression Id. */
  int ROLE = 383;
  /** RegularExpression Id. */
  int ROLLBACK = 384;
  /** RegularExpression Id. */
  int ROLLUP = 385;
  /** RegularExpression Id. */
  int ROUTINE = 386;
  /** RegularExpression Id. */
  int ROUTINE_CATALOG = 387;
  /** RegularExpression Id. */
  int ROUTINE_NAME = 388;
  /** RegularExpression Id. */
  int ROUTINE_SCHEMA = 389;
  /** RegularExpression Id. */
  int ROW = 390;
  /** RegularExpression Id. */
  int ROW_COUNT = 391;
  /** RegularExpression Id. */
  int ROW_NUMBER = 392;
  /** RegularExpression Id. */
  int ROWS = 393;
  /** RegularExpression Id. */
  int SAVEPOINT = 394;
  /** RegularExpression Id. */
  int SCALE = 395;
  /** RegularExpression Id. */
  int SCHEMA = 396;
  /** RegularExpression Id. */
  int SCHEMA_NAME = 397;
  /** RegularExpression Id. */
  int SCOPE = 398;
  /** RegularExpression Id. */
  int SCOPE_CATALOGS = 399;
  /** RegularExpression Id. */
  int SCOPE_NAME = 400;
  /** RegularExpression Id. */
  int SCOPE_SCHEMA = 401;
  /** RegularExpression Id. */
  int SCROLL = 402;
  /** RegularExpression Id. */
  int SEARCH = 403;
  /** RegularExpression Id. */
  int SECOND = 404;
  /** RegularExpression Id. */
  int SECTION = 405;
  /** RegularExpression Id. */
  int SECURITY = 406;
  /** RegularExpression Id. */
  int SELECT = 407;
  /** RegularExpression Id. */
  int SELF = 408;
  /** RegularExpression Id. */
  int SENSITIVE = 409;
  /** RegularExpression Id. */
  int SEQUENCE = 410;
  /** RegularExpression Id. */
  int SERIALIZABLE = 411;
  /** RegularExpression Id. */
  int SERVER = 412;
  /** RegularExpression Id. */
  int SERVER_NAME = 413;
  /** RegularExpression Id. */
  int SESSION = 414;
  /** RegularExpression Id. */
  int SESSION_USER = 415;
  /** RegularExpression Id. */
  int SET = 416;
  /** RegularExpression Id. */
  int SETS = 417;
  /** RegularExpression Id. */
  int SIMILAR = 418;
  /** RegularExpression Id. */
  int SIMPLE = 419;
  /** RegularExpression Id. */
  int SIZE = 420;
  /** RegularExpression Id. */
  int SMALLINT = 421;
  /** RegularExpression Id. */
  int SOME = 422;
  /** RegularExpression Id. */
  int SOURCE = 423;
  /** RegularExpression Id. */
  int SPACE = 424;
  /** RegularExpression Id. */
  int SPECIFIC = 425;
  /** RegularExpression Id. */
  int SPECIFIC_NAME = 426;
  /** RegularExpression Id. */
  int SPECIFICTYPE = 427;
  /** RegularExpression Id. */
  int SQL = 428;
  /** RegularExpression Id. */
  int SQLEXCEPTION = 429;
  /** RegularExpression Id. */
  int SQLSTATE = 430;
  /** RegularExpression Id. */
  int SQLWARNING = 431;
  /** RegularExpression Id. */
  int SQRT = 432;
  /** RegularExpression Id. */
  int START = 433;
  /** RegularExpression Id. */
  int STATE = 434;
  /** RegularExpression Id. */
  int STATEMENT = 435;
  /** RegularExpression Id. */
  int STATIC = 436;
  /** RegularExpression Id. */
  int STDDEV_POP = 437;
  /** RegularExpression Id. */
  int STDDEV_SAMP = 438;
  /** RegularExpression Id. */
  int STRUCTURE = 439;
  /** RegularExpression Id. */
  int STYLE = 440;
  /** RegularExpression Id. */
  int SUBCLASS_ORIGIN = 441;
  /** RegularExpression Id. */
  int SUBMULTISET = 442;
  /** RegularExpression Id. */
  int SUBSTRING = 443;
  /** RegularExpression Id. */
  int SUBSTITUTE = 444;
  /** RegularExpression Id. */
  int SUM = 445;
  /** RegularExpression Id. */
  int SYMMETRIC = 446;
  /** RegularExpression Id. */
  int SYSTEM = 447;
  /** RegularExpression Id. */
  int SYSTEM_USER = 448;
  /** RegularExpression Id. */
  int TABLE = 449;
  /** RegularExpression Id. */
  int TABLE_NAME = 450;
  /** RegularExpression Id. */
  int TABLESAMPLE = 451;
  /** RegularExpression Id. */
  int TEMPORARY = 452;
  /** RegularExpression Id. */
  int THEN = 453;
  /** RegularExpression Id. */
  int TIES = 454;
  /** RegularExpression Id. */
  int TIME = 455;
  /** RegularExpression Id. */
  int TIMESTAMP = 456;
  /** RegularExpression Id. */
  int TIMEZONE_HOUR = 457;
  /** RegularExpression Id. */
  int TIMEZONE_MINUTE = 458;
  /** RegularExpression Id. */
  int TINYINT = 459;
  /** RegularExpression Id. */
  int TO = 460;
  /** RegularExpression Id. */
  int TOP_LEVEL_COUNT = 461;
  /** RegularExpression Id. */
  int TRAILING = 462;
  /** RegularExpression Id. */
  int TRANSACTION = 463;
  /** RegularExpression Id. */
  int TRANSACTIONS_ACTIVE = 464;
  /** RegularExpression Id. */
  int TRANSACTIONS_COMMITTED = 465;
  /** RegularExpression Id. */
  int TRANSACTIONS_ROLLED_BACK = 466;
  /** RegularExpression Id. */
  int TRANSFORM = 467;
  /** RegularExpression Id. */
  int TRANSFORMS = 468;
  /** RegularExpression Id. */
  int TRANSLATE = 469;
  /** RegularExpression Id. */
  int TRANSLATION = 470;
  /** RegularExpression Id. */
  int TREAT = 471;
  /** RegularExpression Id. */
  int TRIGGER = 472;
  /** RegularExpression Id. */
  int TRIGGER_CATALOG = 473;
  /** RegularExpression Id. */
  int TRIGGER_NAME = 474;
  /** RegularExpression Id. */
  int TRIGGER_SCHEMA = 475;
  /** RegularExpression Id. */
  int TRIM = 476;
  /** RegularExpression Id. */
  int TRUE = 477;
  /** RegularExpression Id. */
  int TYPE = 478;
  /** RegularExpression Id. */
  int UESCAPE = 479;
  /** RegularExpression Id. */
  int UNBOUNDED = 480;
  /** RegularExpression Id. */
  int UNCOMMITTED = 481;
  /** RegularExpression Id. */
  int UNDER = 482;
  /** RegularExpression Id. */
  int UNION = 483;
  /** RegularExpression Id. */
  int UNIQUE = 484;
  /** RegularExpression Id. */
  int UNKNOWN = 485;
  /** RegularExpression Id. */
  int UNNAMED = 486;
  /** RegularExpression Id. */
  int UNNEST = 487;
  /** RegularExpression Id. */
  int UPDATE = 488;
  /** RegularExpression Id. */
  int UPPER = 489;
  /** RegularExpression Id. */
  int USAGE = 490;
  /** RegularExpression Id. */
  int USER = 491;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CATALOG = 492;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_CODE = 493;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_NAME = 494;
  /** RegularExpression Id. */
  int USER_DEFINED_TYPE_SCHEMA = 495;
  /** RegularExpression Id. */
  int USING = 496;
  /** RegularExpression Id. */
  int VALUE = 497;
  /** RegularExpression Id. */
  int VALUES = 498;
  /** RegularExpression Id. */
  int VAR_POP = 499;
  /** RegularExpression Id. */
  int VAR_SAMP = 500;
  /** RegularExpression Id. */
  int VARCHAR = 501;
  /** RegularExpression Id. */
  int VARBINARY = 502;
  /** RegularExpression Id. */
  int VARYING = 503;
  /** RegularExpression Id. */
  int VERSION = 504;
  /** RegularExpression Id. */
  int VIEW = 505;
  /** RegularExpression Id. */
  int WHEN = 506;
  /** RegularExpression Id. */
  int WHENEVER = 507;
  /** RegularExpression Id. */
  int WHERE = 508;
  /** RegularExpression Id. */
  int WIDTH_BUCKET = 509;
  /** RegularExpression Id. */
  int WINDOW = 510;
  /** RegularExpression Id. */
  int WITH = 511;
  /** RegularExpression Id. */
  int WITHIN = 512;
  /** RegularExpression Id. */
  int WITHOUT = 513;
  /** RegularExpression Id. */
  int WORK = 514;
  /** RegularExpression Id. */
  int WRAPPER = 515;
  /** RegularExpression Id. */
  int WRITE = 516;
  /** RegularExpression Id. */
  int XML = 517;
  /** RegularExpression Id. */
  int YEAR = 518;
  /** RegularExpression Id. */
  int ZONE = 519;
  /** RegularExpression Id. */
  int UNSIGNED_INTEGER_LITERAL = 520;
  /** RegularExpression Id. */
  int APPROX_NUMERIC_LITERAL = 521;
  /** RegularExpression Id. */
  int DECIMAL_NUMERIC_LITERAL = 522;
  /** RegularExpression Id. */
  int EXPONENT = 523;
  /** RegularExpression Id. */
  int HEXDIGIT = 524;
  /** RegularExpression Id. */
  int WHITESPACE = 525;
  /** RegularExpression Id. */
  int BINARY_STRING_LITERAL = 526;
  /** RegularExpression Id. */
  int QUOTED_STRING = 527;
  /** RegularExpression Id. */
  int PREFIXED_STRING_LITERAL = 528;
  /** RegularExpression Id. */
  int UNICODE_STRING_LITERAL = 529;
  /** RegularExpression Id. */
  int CHARSETNAME = 530;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_ESCAPE_CHAR = 531;
  /** RegularExpression Id. */
  int LPAREN = 532;
  /** RegularExpression Id. */
  int RPAREN = 533;
  /** RegularExpression Id. */
  int LBRACE_D = 534;
  /** RegularExpression Id. */
  int LBRACE_T = 535;
  /** RegularExpression Id. */
  int LBRACE_TS = 536;
  /** RegularExpression Id. */
  int LBRACE_FN = 537;
  /** RegularExpression Id. */
  int LBRACE = 538;
  /** RegularExpression Id. */
  int RBRACE = 539;
  /** RegularExpression Id. */
  int LBRACKET = 540;
  /** RegularExpression Id. */
  int RBRACKET = 541;
  /** RegularExpression Id. */
  int SEMICOLON = 542;
  /** RegularExpression Id. */
  int DOT = 543;
  /** RegularExpression Id. */
  int COMMA = 544;
  /** RegularExpression Id. */
  int EQ = 545;
  /** RegularExpression Id. */
  int GT = 546;
  /** RegularExpression Id. */
  int LT = 547;
  /** RegularExpression Id. */
  int HOOK = 548;
  /** RegularExpression Id. */
  int COLON = 549;
  /** RegularExpression Id. */
  int LE = 550;
  /** RegularExpression Id. */
  int GE = 551;
  /** RegularExpression Id. */
  int NE = 552;
  /** RegularExpression Id. */
  int PLUS = 553;
  /** RegularExpression Id. */
  int MINUS = 554;
  /** RegularExpression Id. */
  int STAR = 555;
  /** RegularExpression Id. */
  int SLASH = 556;
  /** RegularExpression Id. */
  int CONCAT = 557;
  /** RegularExpression Id. */
  int DOUBLE_PERIOD = 558;
  /** RegularExpression Id. */
  int QUOTE = 559;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 560;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 570;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 571;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 572;
  /** RegularExpression Id. */
  int COLLATION_ID = 574;
  /** RegularExpression Id. */
  int IDENTIFIER = 575;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 576;
  /** RegularExpression Id. */
  int UNICODE_QUOTED_IDENTIFIER = 577;
  /** RegularExpression Id. */
  int LETTER = 578;
  /** RegularExpression Id. */
  int DIGIT = 579;
  /** RegularExpression Id. */
  int BEL = 580;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"A\"",
    "\"ABS\"",
    "\"ABSOLUTE\"",
    "\"ACTION\"",
    "\"ADA\"",
    "\"ADD\"",
    "\"ADMIN\"",
    "\"AFTER\"",
    "\"ALL\"",
    "\"ALLOCATE\"",
    "\"ALLOW\"",
    "\"ALWAYS\"",
    "\"ALTER\"",
    "\"AND\"",
    "\"ANY\"",
    "\"ARE\"",
    "\"ARRAY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"ASENSITIVE\"",
    "\"ASSERTION\"",
    "\"ASSIGNMENT\"",
    "\"ASYMMETRIC\"",
    "\"AT\"",
    "\"ATOMIC\"",
    "\"ATTRIBUTE\"",
    "\"ATTRIBUTES\"",
    "\"AUTHORIZATION\"",
    "\"AVG\"",
    "\"BEFORE\"",
    "\"BEGIN\"",
    "\"BERNOULLI\"",
    "\"BETWEEN\"",
    "\"BIGINT\"",
    "\"BINARY\"",
    "\"BIT\"",
    "\"BLOB\"",
    "\"BOOLEAN\"",
    "\"BOTH\"",
    "\"BREADTH\"",
    "\"BY\"",
    "\"C\"",
    "\"CALL\"",
    "\"CALLED\"",
    "\"CARDINALITY\"",
    "\"CASCADE\"",
    "\"CASCADED\"",
    "\"CASE\"",
    "\"CAST\"",
    "\"CATALOG\"",
    "\"CATALOG_NAME\"",
    "\"CEIL\"",
    "\"CEILING\"",
    "\"CHAIN\"",
    "\"CHAR\"",
    "\"CHAR_LENGTH\"",
    "\"CHARACTER\"",
    "\"CHARACTER_LENGTH\"",
    "\"CHARACTER_SET_CATALOG\"",
    "\"CHARACTER_SET_NAME\"",
    "\"CHARACTER_SET_SCHEMA\"",
    "\"CHARACTERISTICTS\"",
    "\"CHARACTERS\"",
    "\"CHECK\"",
    "\"CLASS_ORIGIN\"",
    "\"CLOB\"",
    "\"CLOSE\"",
    "\"COALESCE\"",
    "\"COBOL\"",
    "\"COLLATE\"",
    "\"COLLATION\"",
    "\"COLLATION_CATALOG\"",
    "\"COLLATION_NAME\"",
    "\"COLLATION_SCHEMA\"",
    "\"COLLECT\"",
    "\"COLUMN\"",
    "\"COLUMN_NAME\"",
    "\"COMMAND_FUNCTION\"",
    "\"COMMAND_FUNCTION_CODE\"",
    "\"COMMIT\"",
    "\"COMMITTED\"",
    "\"CONDITION\"",
    "\"CONDITION_NUMBER\"",
    "\"CONNECT\"",
    "\"CONNECTION\"",
    "\"CONNECTION_NAME\"",
    "\"CONSTRAINT\"",
    "\"CONSTRAINT_CATALOG\"",
    "\"CONSTRAINT_NAME\"",
    "\"CONSTRAINT_SCHEMA\"",
    "\"CONSTRAINTS\"",
    "\"CONSTRUCTOR\"",
    "\"CONTAINS\"",
    "\"CONVERT\"",
    "\"CONTINUE\"",
    "\"CORR\"",
    "\"CORRESPONDING\"",
    "\"COUNT\"",
    "\"COVAR_POP\"",
    "\"COVAR_SAMP\"",
    "\"CREATE\"",
    "\"CROSS\"",
    "\"CUBE\"",
    "\"CUME_DIST\"",
    "\"CURRENT\"",
    "\"CURRENT_CATALOG\"",
    "\"CURRENT_DATE\"",
    "\"CURRENT_DEFAULT_TRANSFORM_GROUP\"",
    "\"CURRENT_PATH\"",
    "\"CURRENT_ROLE\"",
    "\"CURRENT_SCHEMA\"",
    "\"CURRENT_TIME\"",
    "\"CURRENT_TIMESTAMP\"",
    "\"CURRENT_TRANSFORM_GROUP_FOR_TYPE\"",
    "\"CURRENT_USER\"",
    "\"CURSOR\"",
    "\"CURSOR_NAME\"",
    "\"CYCLE\"",
    "\"DATA\"",
    "\"DATE\"",
    "\"DATETIME_INTERVAL_CODE\"",
    "\"DATETIME_INTERVAL_PRECISION\"",
    "\"DAY\"",
    "\"DEALLOCATE\"",
    "\"DEC\"",
    "\"DECIMAL\"",
    "\"DECLARE\"",
    "\"DEFAULT\"",
    "\"DEFAULTS\"",
    "\"DEFERRABLE\"",
    "\"DEFERRED\"",
    "\"DEFINED\"",
    "\"DEFINER\"",
    "\"DEGREE\"",
    "\"DELETE\"",
    "\"DENSE_RANK\"",
    "\"DEPTH\"",
    "\"DEREF\"",
    "\"DERIVED\"",
    "\"DESCRIBE\"",
    "\"DESC\"",
    "\"DESCRIPTION\"",
    "\"DESCRIPTOR\"",
    "\"DETERMINISTIC\"",
    "\"DIAGNOSTICS\"",
    "\"DISALLOW\"",
    "\"DISCONNECT\"",
    "\"DISPATCH\"",
    "\"DISTINCT\"",
    "\"DOMAIN\"",
    "\"DOUBLE\"",
    "\"DROP\"",
    "\"DYNAMIC\"",
    "\"DYNAMIC_FUNCTION\"",
    "\"DYNAMIC_FUNCTION_CODE\"",
    "\"EACH\"",
    "\"ELEMENT\"",
    "\"ELSE\"",
    "\"END\"",
    "\"END-EXEC\"",
    "\"EQUALS\"",
    "\"ESCAPE\"",
    "\"EVERY\"",
    "\"EXCEPT\"",
    "\"EXCEPTION\"",
    "\"EXCLUDE\"",
    "\"EXCLUDING\"",
    "\"EXEC\"",
    "\"EXECUTE\"",
    "\"EXISTS\"",
    "\"EXP\"",
    "\"EXPLAIN\"",
    "\"EXTERNAL\"",
    "\"EXTRACT\"",
    "\"FALSE\"",
    "\"FETCH\"",
    "\"FILTER\"",
    "\"FINAL\"",
    "\"FIRST\"",
    "\"FIRST_VALUE\"",
    "\"FLOAT\"",
    "\"FLOOR\"",
    "\"FOLLOWING\"",
    "\"FOR\"",
    "\"FOREIGN\"",
    "\"FORTRAN\"",
    "\"FOUND\"",
    "\"FREE\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"FUNCTION\"",
    "\"FUSION\"",
    "\"G\"",
    "\"GENERAL\"",
    "\"GENERATED\"",
    "\"GET\"",
    "\"GLOBAL\"",
    "\"GO\"",
    "\"GOTO\"",
    "\"GRANT\"",
    "\"GRANTED\"",
    "\"GROUP\"",
    "\"GROUPING\"",
    "\"HAVING\"",
    "\"HIERARCHY\"",
    "\"HOLD\"",
    "\"HOUR\"",
    "\"IDENTITY\"",
    "\"IMMEDIATE\"",
    "\"IMPLEMENTATION\"",
    "\"IMPORT\"",
    "\"IN\"",
    "\"INDICATOR\"",
    "\"INCLUDING\"",
    "\"INCREMENT\"",
    "\"INITIALLY\"",
    "\"INNER\"",
    "\"INOUT\"",
    "\"INPUT\"",
    "\"INSENSITIVE\"",
    "\"INSERT\"",
    "\"INSTANCE\"",
    "\"INSTANTIABLE\"",
    "\"INT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTERSECTION\"",
    "\"INTERVAL\"",
    "\"INTO\"",
    "\"INVOKER\"",
    "\"IS\"",
    "\"ISOLATION\"",
    "\"JAVA\"",
    "\"JOIN\"",
    "\"K\"",
    "\"KEY\"",
    "\"KEY_MEMBER\"",
    "\"KEY_TYPE\"",
    "\"LABEL\"",
    "\"LANGUAGE\"",
    "\"LARGE\"",
    "\"LAST\"",
    "\"LAST_VALUE\"",
    "\"LATERAL\"",
    "\"LEADING\"",
    "\"LEFT\"",
    "\"LENGTH\"",
    "\"LEVEL\"",
    "\"LIBRARY\"",
    "\"LIKE\"",
    "\"LIMIT\"",
    "\"LN\"",
    "\"LOCAL\"",
    "\"LOCALTIME\"",
    "\"LOCALTIMESTAMP\"",
    "\"LOCATOR\"",
    "\"LOWER\"",
    "\"M\"",
    "\"MAP\"",
    "\"MATCH\"",
    "\"MATCHED\"",
    "\"MAX\"",
    "\"MAXVALUE\"",
    "\"MEMBER\"",
    "\"MERGE\"",
    "\"MESSAGE_LENGTH\"",
    "\"MESSAGE_OCTET_LENGTH\"",
    "\"MESSAGE_TEXT\"",
    "\"METHOD\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINVALUE\"",
    "\"MOD\"",
    "\"MODIFIES\"",
    "\"MODULE\"",
    "\"MONTH\"",
    "\"MORE\"",
    "\"MULTISET\"",
    "\"MUMPS\"",
    "\"NAME\"",
    "\"NAMES\"",
    "\"NATIONAL\"",
    "\"NATURAL\"",
    "\"NCHAR\"",
    "\"NCLOB\"",
    "\"NESTING\"",
    "\"NEW\"",
    "\"NEXT\"",
    "\"NO\"",
    "\"NONE\"",
    "\"NORMALIZE\"",
    "\"NORMALIZED\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"NULLABLE\"",
    "\"NULLIF\"",
    "\"NULLS\"",
    "\"NUMBER\"",
    "\"NUMERIC\"",
    "\"OBJECT\"",
    "\"OCTET_LENGTH\"",
    "\"OCTETS\"",
    "\"OF\"",
    "\"OLD\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OPEN\"",
    "\"OPTION\"",
    "\"OPTIONS\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"ORDERING\"",
    "\"ORDINALITY\"",
    "\"OTHERS\"",
    "\"OUT\"",
    "\"OUTER\"",
    "\"OUTPUT\"",
    "\"OVER\"",
    "\"OVERLAPS\"",
    "\"OVERLAY\"",
    "\"OVERRIDING\"",
    "\"PAD\"",
    "\"PARAMETER\"",
    "\"PARAMETER_MODE\"",
    "\"PARAMETER_NAME\"",
    "\"PARAMETER_ORDINAL_POSITION\"",
    "\"PARAMETER_SPECIFIC_CATALOG\"",
    "\"PARAMETER_SPECIFIC_NAME\"",
    "\"PARAMETER_SPECIFIC_SCHEMA\"",
    "\"PARTIAL\"",
    "\"PARTITION\"",
    "\"PASCAL\"",
    "\"PASSTHROUGH\"",
    "\"PATH\"",
    "\"PERCENT_RANK\"",
    "\"PERCENTILE_CONT\"",
    "\"PERCENTILE_DISC\"",
    "\"PLACING\"",
    "\"PLAN\"",
    "\"PLI\"",
    "\"POSITION\"",
    "\"POWER\"",
    "\"PRECEDING\"",
    "\"PRECISION\"",
    "\"PREPARE\"",
    "\"PRESERVE\"",
    "\"PRIMARY\"",
    "\"PRIOR\"",
    "\"PRIVILEGES\"",
    "\"PROCEDURE\"",
    "\"PUBLIC\"",
    "\"RANGE\"",
    "\"RANK\"",
    "\"READ\"",
    "\"READS\"",
    "\"REAL\"",
    "\"RECURSIVE\"",
    "\"REF\"",
    "\"REFERENCES\"",
    "\"REFERENCING\"",
    "\"REGR_AVGX\"",
    "\"REGR_AVGY\"",
    "\"REGR_COUNT\"",
    "\"REGR_INTERCEPT\"",
    "\"REGR_R2\"",
    "\"REGR_SLOPE\"",
    "\"REGR_SXX\"",
    "\"REGR_SXY\"",
    "\"RELATIVE\"",
    "\"RELEASE\"",
    "\"REPEATABLE\"",
    "\"RESTART\"",
    "\"RESTRICT\"",
    "\"RESULT\"",
    "\"RETURN\"",
    "\"RETURNED_CARDINALITY\"",
    "\"RETURNED_LENGTH\"",
    "\"RETURNED_OCTET_LENGTH\"",
    "\"RETURNED_SQLSTATE\"",
    "\"RETURNS\"",
    "\"REVOKE\"",
    "\"RIGHT\"",
    "\"ROLE\"",
    "\"ROLLBACK\"",
    "\"ROLLUP\"",
    "\"ROUTINE\"",
    "\"ROUTINE_CATALOG\"",
    "\"ROUTINE_NAME\"",
    "\"ROUTINE_SCHEMA\"",
    "\"ROW\"",
    "\"ROW_COUNT\"",
    "\"ROW_NUMBER\"",
    "\"ROWS\"",
    "\"SAVEPOINT\"",
    "\"SCALE\"",
    "\"SCHEMA\"",
    "\"SCHEMA_NAME\"",
    "\"SCOPE\"",
    "\"SCOPE_CATALOGS\"",
    "\"SCOPE_NAME\"",
    "\"SCOPE_SCHEMA\"",
    "\"SCROLL\"",
    "\"SEARCH\"",
    "\"SECOND\"",
    "\"SECTION\"",
    "\"SECURITY\"",
    "\"SELECT\"",
    "\"SELF\"",
    "\"SENSITIVE\"",
    "\"SEQUENCE\"",
    "\"SERIALIZABLE\"",
    "\"SERVER\"",
    "\"SERVER_NAME\"",
    "\"SESSION\"",
    "\"SESSION_USER\"",
    "\"SET\"",
    "\"SETS\"",
    "\"SIMILAR\"",
    "\"SIMPLE\"",
    "\"SIZE\"",
    "\"SMALLINT\"",
    "\"SOME\"",
    "\"SOURCE\"",
    "\"SPACE\"",
    "\"SPECIFIC\"",
    "\"SPECIFIC_NAME\"",
    "\"SPECIFICTYPE\"",
    "\"SQL\"",
    "\"SQLEXCEPTION\"",
    "\"SQLSTATE\"",
    "\"SQLWARNING\"",
    "\"SQRT\"",
    "\"START\"",
    "\"STATE\"",
    "\"STATEMENT\"",
    "\"STATIC\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STRUCTURE\"",
    "\"STYLE\"",
    "\"SUBCLASS_ORIGIN\"",
    "\"SUBMULTISET\"",
    "\"SUBSTRING\"",
    "\"SUBSTITUTE\"",
    "\"SUM\"",
    "\"SYMMETRIC\"",
    "\"SYSTEM\"",
    "\"SYSTEM_USER\"",
    "\"TABLE\"",
    "\"TABLE_NAME\"",
    "\"TABLESAMPLE\"",
    "\"TEMPORARY\"",
    "\"THEN\"",
    "\"TIES\"",
    "\"TIME\"",
    "\"TIMESTAMP\"",
    "\"TIMEZONE_HOUR\"",
    "\"TIMEZONE_MINUTE\"",
    "\"TINYINT\"",
    "\"TO\"",
    "\"TOP_LEVEL_COUNT\"",
    "\"TRAILING\"",
    "\"TRANSACTION\"",
    "\"TRANSACTIONS_ACTIVE\"",
    "\"TRANSACTIONS_COMMITTED\"",
    "\"TRANSACTIONS_ROLLED_BACK\"",
    "\"TRANSFORM\"",
    "\"TRANSFORMS\"",
    "\"TRANSLATE\"",
    "\"TRANSLATION\"",
    "\"TREAT\"",
    "\"TRIGGER\"",
    "\"TRIGGER_CATALOG\"",
    "\"TRIGGER_NAME\"",
    "\"TRIGGER_SCHEMA\"",
    "\"TRIM\"",
    "\"TRUE\"",
    "\"TYPE\"",
    "\"UESCAPE\"",
    "\"UNBOUNDED\"",
    "\"UNCOMMITTED\"",
    "\"UNDER\"",
    "\"UNION\"",
    "\"UNIQUE\"",
    "\"UNKNOWN\"",
    "\"UNNAMED\"",
    "\"UNNEST\"",
    "\"UPDATE\"",
    "\"UPPER\"",
    "\"USAGE\"",
    "\"USER\"",
    "\"USER_DEFINED_TYPE_CATALOG\"",
    "\"USER_DEFINED_TYPE_CODE\"",
    "\"USER_DEFINED_TYPE_NAME\"",
    "\"USER_DEFINED_TYPE_SCHEMA\"",
    "\"USING\"",
    "\"VALUE\"",
    "\"VALUES\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"VARCHAR\"",
    "\"VARBINARY\"",
    "\"VARYING\"",
    "\"VERSION\"",
    "\"VIEW\"",
    "\"WHEN\"",
    "\"WHENEVER\"",
    "\"WHERE\"",
    "\"WIDTH_BUCKET\"",
    "\"WINDOW\"",
    "\"WITH\"",
    "\"WITHIN\"",
    "\"WITHOUT\"",
    "\"WORK\"",
    "\"WRAPPER\"",
    "\"WRITE\"",
    "\"XML\"",
    "\"YEAR\"",
    "\"ZONE\"",
    "<UNSIGNED_INTEGER_LITERAL>",
    "<APPROX_NUMERIC_LITERAL>",
    "<DECIMAL_NUMERIC_LITERAL>",
    "<EXPONENT>",
    "<HEXDIGIT>",
    "<WHITESPACE>",
    "<BINARY_STRING_LITERAL>",
    "<QUOTED_STRING>",
    "<PREFIXED_STRING_LITERAL>",
    "<UNICODE_STRING_LITERAL>",
    "<CHARSETNAME>",
    "<UNICODE_QUOTED_ESCAPE_CHAR>",
    "\"(\"",
    "\")\"",
    "<LBRACE_D>",
    "<LBRACE_T>",
    "<LBRACE_TS>",
    "<LBRACE_FN>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"?\"",
    "\":\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"||\"",
    "\"..\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 566>",
    "\"//\"",
    "\"--\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 573>",
    "<COLLATION_ID>",
    "<IDENTIFIER>",
    "<QUOTED_IDENTIFIER>",
    "<UNICODE_QUOTED_IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<BEL>",
  };

}
